var Scroller=Class.create();Scroller.ids={};Scroller.i=0;
Scroller.prototype={initialize:function(a){this.outerBox=a;this.decorate()},decorate:function(){$(this.outerBox).makePositioned();Scroller.i+=1;this.myIndex=Scroller.i;this.innerBox=document.createElement("DIV");this.innerBox.className="scroll-innerBox";$(this.innerBox).makePositioned();this.innerBox.style.cssFloat=this.innerBox.style.styleFloat="left";this.innerBox.id="scroll-innerBox-"+Scroller.i;for(this.innerBox.style.top="0px";this.outerBox.hasChildNodes();)this.innerBox.appendChild(this.outerBox.firstChild);this.innerBox.style.overflow=
"hidden";this.outerBox.style.overflow="hidden";this.track=document.createElement("div");this.track.className="scroll-track";$(this.track).makePositioned();this.track.style.cssFloat=this.track.style.styleFloat="left";this.track.id="scroll-track-"+Scroller.i;this.track.appendChild(document.createComment(""));this.tracktop=document.createElement("div");this.tracktop.className="scroll-track-top";$(this.tracktop).makePositioned();this.tracktop.style.cssFloat=this.tracktop.style.styleFloat="left";this.tracktop.id=
"scroll-track-top-"+Scroller.i;this.tracktop.appendChild(document.createComment(""));this.trackbot=document.createElement("div");this.trackbot.className="scroll-track-bot";$(this.trackbot).makePositioned();this.trackbot.style.cssFloat=this.trackbot.style.styleFloat="left";this.trackbot.id="scroll-track-bot-"+Scroller.i;this.trackbot.appendChild(document.createComment(""));this.handle=document.createElement("div");this.handle.className="scroll-handle-container";this.handle.id="scroll-handle-container"+
Scroller.i;this.handle_middle=document.createElement("div");this.handle_middle.className="scroll-handle";$(this.handle_middle).makePositioned();this.handle_middle.id="scroll-handle-"+Scroller.i;this.handle_middle.appendChild(document.createComment(""));this.handletop=document.createElement("div");this.handletop.className="scroll-handle-top";$(this.handletop).makePositioned();this.handletop.id="scroll-handle-top-"+Scroller.i;this.handletop.appendChild(document.createComment(""));this.handlebot=document.createElement("div");
this.handlebot.className="scroll-handle-bot";$(this.handlebot).makePositioned();this.handlebot.id="scroll-handle-bot-"+Scroller.i;this.handlebot.appendChild(document.createComment(""));this.track.hide();this.tracktop.hide();this.trackbot.hide();this.outerBox.appendChild(this.innerBox);this.outerBox.appendChild(this.tracktop);this.handle.appendChild(this.handletop);this.handle.appendChild(this.handle_middle);this.handle.appendChild(this.handlebot);this.track.appendChild(this.handle);this.outerBox.appendChild(this.track);
this.outerBox.appendChild(this.trackbot);this.slider=new Control.Slider($(this.handle).id,$(this.track).id,{axis:"vertical",minimum:0,maximum:$(this.outerBox).clientHeight});this.slider.options.onSlide=this.slider.options.onChange=this.onChange.bind(this);setTimeout(this.resetScrollbar.bind(this,false),10);this.domMouseCB=this.MouseWheelEvent.bindAsEventListener(this,this.slider);this.mouseWheelCB=this.MouseWheelEvent.bindAsEventListener(this,this.slider);this.trackTopCB=this.tracktopEvent.bindAsEventListener(this,
this.slider);this.trackBotCB=this.trackbotEvent.bindAsEventListener(this,this.slider);$(this.outerBox).observe("DOMMouseScroll",this.domMouseCB);$(this.outerBox).observe("mousewheel",this.mouseWheelCB);$(this.tracktop).observe("mousedown",this.trackTopCB);$(this.trackbot).observe("mousedown",this.trackBotCB)},release:function(){$(this.outerBox).stopObserving("DOMMouseScroll",this.domMouseCB);$(this.outerBox).stopObserving("mousewheel",this.mouseWheelCB);$(this.tracktop).stopObserving("mousedown",
this.trackTopCB);$(this.trackbot).stopObserving("mousedown",this.trackBotCB)},resetScrollbar:function(a){this.track.hide();this.tracktop.hide();this.trackbot.hide();this.enableScroll=false;this.innerHeight=$(this.outerBox).clientHeight;this.innerBox.style.height=this.innerHeight+"px";var b=$(this.outerBox).clientWidth,c=Element.getStyle(this.tracktop,"height");c=c?c.replace("px",""):0;var d=Element.getStyle(this.handletop,"height");d=d?d.replace("px",""):0;if(this.innerHeight<this.innerBox.scrollHeight){this.viewportHeight=
this.innerHeight-c*2;this.slider.trackLength=this.viewportHeight;this.track.style.height=this.viewportHeight+"px";this.handleHeight=Math.round(this.viewportHeight*this.innerHeight/this.innerBox.scrollHeight);if(this.handleHeight<d*2)this.handleHeight=d*2;if(this.handleHeight<10)this.handleHeight=10;this.handle.style.height=this.handleHeight+"px";this.handle_middle.style.height=this.handleHeight-d*2+"px";this.handletop.style.height=d+"px";this.slider.handleLength=this.handleHeight;this.track.style.display=
"inline";this.tracktop.style.display="inline";this.trackbot.style.display="inline";this.ieDecreaseBy=1;if(this.outerBox.currentStyle){b=this.outerBox.currentStyle.borderWidth.replace("px","");if(!isNaN(b))this.ieDecreaseBy=b*2}b=$(this.outerBox).clientWidth-$(this.track).clientWidth-this.ieDecreaseBy;this.enableScroll=true}this.innerBox.style.width=b+"px";a&&setTimeout(this.resetScrollbar.bind(this,false),10)},MouseWheelEvent:function(a,b){var c=0;if(!a)a=window.event;if(a.wheelDelta)c=a.wheelDelta/
120;else if(a.detail)c=-a.detail/3;c&&b.setValueBy(-c/10);Event.stop(a)},trackbotEvent:function(a,b){if(Event.isLeftClick(a)){b.setValueBy(0.2);Event.stop(a)}},tracktopEvent:function(a,b){if(Event.isLeftClick(a)){b.setValueBy(-0.2);Event.stop(a)}},onChange:function(a){if(this.enableScroll)this.innerBox.scrollTop=Math.round(a*(this.innerBox.scrollHeight-this.innerBox.offsetHeight))}};Scroller.setAll=function(){$$(".makeScroll").each(function(a){Scroller.ids[a.id]=new Scroller(a)})};
Scroller.reset=function(a){if($(a).className.match(/(^|\s)makeScroll(\s|$)/)){Scroller.ids[a]&&Scroller.ids[a].release();Scroller.ids[a]=new Scroller($(a))}};Scroller.updateAll=function(){$H(Scroller.ids).each(function(a){Scroller.ids[a.key].resetScrollbar(true)})};if(typeof Effect=="undefined")throw"You must have the script.aculo.us library to use this accordion";
var Accordion=Class.create({initialize:function(a,b){if(!$(a))throw"Attempted to initalize accordion with id: "+a+" which was not found.";this.accordion=$(a);this.options={toggleClass:"accordion-toggle",toggleActive:"accordion-toggle-active",contentClass:"accordion-content"};this.contents=this.accordion.select("div."+this.options.contentClass);this.isAnimating=false;this.maxHeight=300;this.current=b?this.contents[b-1]:this.contents[0];this.toExpand=null;this.checkMaxHeight();this.initialHide();this.attachInitialMaxHeight();
this.accordion.observe("click",this.clickHandler.bindAsEventListener(this))},expand:function(a){this.toExpand=a.next("div."+this.options.contentClass);if(this.current!=this.toExpand){this.toExpand.show();this.animate()}},checkMaxHeight:function(){for(var a=0;a<this.contents.length;a++)if(this.contents[a].getHeight()>this.maxHeight)this.maxHeight=this.contents[a].getHeight()},attachInitialMaxHeight:function(){this.current.previous("div."+this.options.toggleClass).addClassName(this.options.toggleActive);
this.current.getHeight()!=this.maxHeight&&this.current.setStyle({height:"300px"})},clickHandler:function(a){a=a.element();a.hasClassName(this.options.toggleClass)&&!this.isAnimating&&this.expand(a)},initialHide:function(){for(var a=0;a<this.contents.length;a++)if(this.contents[a]!=this.current){this.contents[a].hide();this.contents[a].setStyle({height:0})}},animate:function(){var a=[],b={sync:true,scaleFrom:0,scaleContent:false,transition:Effect.Transitions.sinoidal,scaleMode:{originalHeight:300,
originalWidth:this.accordion.getWidth()},scaleX:false,scaleY:true};a.push(new Effect.Scale(this.toExpand,100,b));b={sync:true,scaleContent:false,transition:Effect.Transitions.sinoidal,scaleX:false,scaleY:true};a.push(new Effect.Scale(this.current,0,b));new Effect.Parallel(a,{duration:0.75,fps:35,queue:{position:"end",scope:"accordion"},beforeStart:function(){Scroller.updateAll();this.isAnimating=true;this.current.previous("div."+this.options.toggleClass).removeClassName(this.options.toggleActive);
this.toExpand.previous("div."+this.options.toggleClass).addClassName(this.options.toggleActive)}.bind(this),afterFinish:function(){this.current.hide();this.toExpand.setStyle({height:"300px"});this.current=this.toExpand;this.isAnimating=false}.bind(this)})}});