# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2748289d4bf924635bff7b9bb3ab03de4dd6227ff23a91244fcc9e0f9ec3d4063bb7e35429c8a438755b3722fc5d27d218dbc453cbfb3011b2942f783a0814f

test:
  secret_key_base: ffd903ef256a4879a3895568610283bbbe39bf37a00577a5c84f83e19e0170013b9c70153e2461d5b2db0c7891a7a0b60b31429c024f1a705516befc9e201e23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
